dataset:
  train_path: "D:/stage3/nsynth/nsynth-train/"
  valid_path: "D:/stage3/nsynth/nsynth-valid/"
  test_path: "D:/stage3/nsynth/nsynth-test/"
  train_subset_files: "nsynth_bass_subset/keys_bass_train.txt"
  valid_subset_files: "nsynth_bass_subset/keys_bass_valid.txt"
  test_subset_files: "nsynth_bass_subset/keys_bass_test.txt"
  metadata: "examples.json"
  audio: "audio/"
  pitch: "pitch/"
  loudness: "loudness/"

common:
  sampling_rate: 16000
  block_size: 160
  duration_secs: 4
  global_seed:  28

train:
  batch_size: 128
  scales: [4096, 2048, 1024, 512, 256, 128]
  overlap: .75
  start_lr: 0.001
  stop_lr: 0.0001
  decay_over: 400000
  hidden_size: 512
  n_harmonic: 100
  n_bands: 65
  n_wavetables: 20
  n_mfcc: 30
  epochs: 100
  

test:
  batch_size: 2
  scales: [4096, 2048, 1024, 512, 256, 128]
  overlap: .75
  hidden_size: 512
  n_harmonic: 100
  n_bands: 65
  n_wavetables: 20
  n_mfcc: 30

crepe:
  model: "full"

visualize: false
